### ISSUE TITLE
Bots Healthcheck on the Api

### ISSUE THREAD

**Issue by benkio** [benkio/myTelegramBot#731]
# Problem

I have several telegram bots and I want to add to the github action for deploying them a step that health check if they are actually running fine or not. How can I do it? is there an api endpoint I can use? or shall I check the process to be up and running on the virtual machine? 

# AI Answer

To add a health check step for your Telegram bots in a GitHub Actions workflow, you need to verify that the bots are running correctly after deployment. You can achieve this by either querying the Telegram Bot API to check the bot's responsiveness or checking the process status on the virtual machine (VM) where the bot is deployed. Below, I’ll outline both approaches, focusing on the Telegram Bot API method as it directly tests the bot’s functionality, and briefly cover the process check method. I’ll also provide a sample GitHub Actions workflow step.

### Recommended Approach: Using the Telegram Bot API
The Telegram Bot API provides a simple endpoint, `getMe`, which allows you to verify if your bot is operational by checking if it can respond with its own information (e.g., username, ID). This is the most reliable way to confirm that your bot is running and can communicate with Telegram’s servers.

#### Steps to Implement the API Health Check
1. **Use the `getMe` Endpoint**:
   - Endpoint: `https://api.telegram.org/bot<token>/getMe`
   - This endpoint returns a JSON object with the bot’s details if the bot is running and the token is valid.
   - A successful response includes an `"ok": true` field and a `result` object with bot details (e.g., `id`, `username`).
   - A failed response (e.g., 401 Unauthorized or 429 Too Many Requests) indicates the bot is either not running, the token is invalid, or the bot is rate-limited.

2. **Add a Health Check Step in GitHub Actions**:
   - Use a `curl` command or a script (e.g., Python or Bash) to call the `getMe` endpoint.
   - Check the response to ensure it contains `"ok": true`.
   - Store your bot token securely in GitHub Secrets to avoid exposing it in the workflow.

3. **Handle Rate Limits**:
   - Telegram imposes rate limits (e.g., 1 request per second per chat, 30 messages per second overall). Ensure your health check respects these limits to avoid 429 errors. A single `getMe` call per bot should generally be safe.[](https://rollout.com/integration-guides/telegram-bot-api/api-essentials)

#### Sample GitHub Actions Workflow
Here’s an example of a GitHub Actions workflow that includes a health check step for a Telegram bot using the `getMe` endpoint:

```yaml
name: Deploy Telegram Bot with Health Check

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Deploy your bot (example: assuming deployment to a VM or server)
      - name: Deploy bot
        run: |
          # Your deployment commands here (e.g., SSH to VM, restart service, etc.)
          echo "Deploying bot..."

      # Health check for Telegram bot
      - name: Health check Telegram bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          RESPONSE=$(curl -s "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getMe")
          if echo "$RESPONSE" | grep -q '"ok":true'; then
            echo "Bot is healthy!"
          else
            echo "Bot health check failed: $RESPONSE"
            exit 1
          fi
```

**Explanation**:
- **Secrets**: Store your bot token in GitHub Secrets (`TELEGRAM_BOT_TOKEN`) for security.
- **Curl Command**: The `curl -s` command silently fetches the response from the `getMe` endpoint.
- **Response Check**: The `grep -q '"ok":true'` checks if the response contains `"ok":true`. If not, the step fails and outputs the response for debugging.
- **Exit Code**: If the health check fails, `exit 1` causes the workflow to fail, alerting you to the issue.

#### Handling Multiple Bots
If you have multiple Telegram bots, you can loop through their tokens in the health check step. Store each bot’s token in GitHub Secrets (e.g., `TELEGRAM_BOT_TOKEN_1`, `TELEGRAM_BOT_TOKEN_2`, etc.), and use a script to iterate:

```yaml
      - name: Health check multiple Telegram bots
        env:
          BOT_TOKENS: ${{ secrets.TELEGRAM_BOT_TOKEN_1 }} ${{ secrets.TELEGRAM_BOT_TOKEN_2 }}
        run: |
          for TOKEN in $BOT_TOKENS; do
            RESPONSE=$(curl -s "https://api.telegram.org/bot${TOKEN}/getMe")
            if echo "$RESPONSE" | grep -q '"ok":true'; then
              echo "Bot with token ending ${TOKEN: -10} is healthy!"
            else
              echo "Bot with token ending ${TOKEN: -10} health check failed: $RESPONSE"
              exit 1
            fi
          done
```

### Alternative Approach: Checking the Process on the VM
If you prefer to check whether the bot’s process is running on the VM, you can add a step to verify the process status. This is less reliable than the API check because it doesn’t confirm if the bot is actually communicating with Telegram, but it can be useful as a secondary check.

#### Steps for Process Check
1. **Identify the Process**:
   - Determine how your bot runs (e.g., as a Python script, Node.js app, or Docker container).
   - For example, if your bot is a Python script, it might run as `python3 bot.py`.

2. **Check Process Status**:
   - Use SSH in your GitHub Actions workflow to connect to the VM and run a command like `pgrep` or `ps` to check if the process is running.
   - Alternatively, if using Docker, check if the container is up with `docker ps`.

3. **Example Workflow Step**:
   Assuming you’re using SSH to access the VM and the bot runs as a Python process:

```yaml
      - name: Check bot process on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            if pgrep -f "python3 bot.py" > /dev/null; then
              echo "Bot process is running!"
            else
              echo "Bot process is not running!"
              exit 1
            fi
```

**Explanation**:
- **SSH Action**: Uses the `appleboy/ssh-action` to connect to your VM.
- **Secrets**: Store the VM host, username, and SSH key in GitHub Secrets.
- **Process Check**: The `pgrep -f "python3 bot.py"` command checks if the bot process is running. If not, the step fails.

#### Limitations of Process Check
- **False Positives**: A running process doesn’t guarantee the bot is functional (e.g., it might be stuck or unable to connect to Telegram).
- **Environment-Specific**: Requires SSH access and knowledge of the process name or container ID, which may vary across deployments.
- **Security**: Ensure SSH credentials are securely stored in GitHub Secrets.

### Additional Considerations
- **Combine Both Methods**: For robust monitoring, you can use both the API check (primary) and process check (secondary). The API check confirms functionality, while the process check ensures the bot is running on the VM.
- **Rate Limiting**: Be cautious with frequent API calls. If running health checks for multiple bots, stagger them to avoid hitting Telegram’s rate limits (e.g., 30 requests per second overall).[](https://rollout.com/integration-guides/telegram-bot-api/api-essentials)
- **Logging**: Log the health check results for debugging. You can use GitHub Actions’ built-in logging or send notifications (e.g., via Telegram or Slack) if a check fails.[](https://github.com/appleboy/telegram-action)[](https://medium.com/%40joaogabrielpadilha/how-to-integrate-github-actions-with-slack-telegram-and-whatsapp-67a4dca0f17d)
- **Custom Health Endpoint**: If your bot has a custom health endpoint (e.g., a `/health` route in a web server), you can query it instead of or in addition to the `getMe` endpoint.
- **Monitoring Tools**: For ongoing monitoring beyond GitHub Actions, consider tools like BotMon (a Telegram bot for monitoring other bots) or external services like UptimeRobot to periodically check the `getMe` endpoint.[](https://stackoverflow.com/questions/75618509/is-there-a-monitoring-system-for-health-checking-a-telegram-bot)

### Recommendation
The Telegram Bot API `getMe` endpoint is the most straightforward and reliable way to health check your bots, as it directly tests their ability to interact with Telegram. Add a step in your GitHub Actions workflow to call this endpoint for each bot, using the sample code provided. If you need to verify the process is running on the VM, use the process check as a secondary measure, but prioritize the API check for accuracy.

If you need further customization (e.g., specific bot commands to test or integration with a monitoring system), let me know, and I can provide additional details!
